name: CryptoExchange API CI

# Trigger workflow on push / pull request 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code   
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'          
          distribution: 'zulu'          
          cache: maven

      # Step 3: Cache Maven dependencies (speed build)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build project, run tests
      - name: Build and run tests with Maven
        run: mvn clean install
        

      # Step 5: SonarCloud Sca (code quality) 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  #  SonarCloud token added as github secret
        with:
          args: >
            -Dsonar.projectKey=<your-sonarcloud-project-key>
            -Dsonar.organization=<your-sonarcloud-organization>
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src
